# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

formats: all

sphinx:
  builder: html
  configuration: doc/conf.py

python:
  version: 3.6
  install:
    - requirements: requirements-dev.txt
    - method: pip
      path: .
